export const BACKDROP_URL = 'https://image.tmdb.org/t/p/w1280'
export const BACKDROP_URL_LARGE = 'https://image.tmdb.org/t/p/original'
export const POSTER_URL = 'https://image.tmdb.org/t/p/w342'
export const FEATURE_LOGO_URL = '/media'
export const FEATURE_VIDEO_URL = '/media'